### ISSUE TITLE
P68./P69

### ISSUE THREAD

**Issue by guider** [bboyfeiyu/android-jtm-issues#1]
P68 ： Lopper -->>Looper

P69 : PrePare--->>prepare

**Comment by tzrgaga** [comment]
P7：为了更好地运用越来越大的**屏幕控件** -->>为了更好地运用越来越大的 **屏幕空间**

**Comment by hehonghui** [comment]
@guider 多谢提交，已经添加到勘误列表。 :)

**Comment by liwenkun** [comment]
P24: 第一行<providerandroid:name=..../>     -->>      <provider android:name=.../>

**Comment by liwenkun** [comment]
P29: 第三行 //有视图缓存，复用**属兔** -->> //有视图缓存，复用**视图**

**Comment by liwenkun** [comment]
P38:第二段第二行，“在measureDrawable函数中，我们通过在xml文件中指定**。**资源id对应的Drawable得到图片的<b>高度</b>和高度...”   -->> "在measureDrawable函数中，我们通过在xml文件中指定资源id对应的Drawable得到图片的**宽度**和高度...“

**Comment by liwenkun** [comment]
P38：倒数第二行”我们都知道Android的**视图数**..." -->> "我们都知道Android的**视图树**..."

**Comment by hehonghui** [comment]
@Lwenkun 多谢提交哈，后续还有问题你可以单独提一个issue 。

**Comment by realxz** [comment]
P47:第一段，scrollTo(100),应该是在y轴上向上滚动100个像素点吧

**Comment by liwenkun** [comment]
P58:文字倒数第二行：“<b>自动化</b>” -->> "<b>子动画</b>"
P60:第二段第三行：”<b>android:fromYScale</b>" -->> "<b>android:fromYDelta</b>"
P65:文字第五段第三行：“逐渐增大<b>统一</b>时间段” -->> "逐渐增大<b>同一</b>时间段“;同时怀疑这段表意不清。
P65:文字倒数第一段第四行：“它与t为**300**毫秒的x差值为5。” -->> “它与t为**200**毫秒的x差值为5。”

**Comment by hehonghui** [comment]
@realxz 多谢提交，我晚上审核一下。 :)
